--  begin  test.data
--  applying  mysql_data.gram
TRUNCATE TABLE `game`.`payouts`;
ALTER TABLE `game`.`payouts` AUTO_INCREMENT = 1;
INSERT INTO `game`.`payouts` ( `code`,`payid`,`quanity`,`type`,`linked`,`linked_chance`,`description`,`exp`) VALUES 
("1 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("2 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("3 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("4 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("5 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("6 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("7 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("8 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("9 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("10 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("11 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("12 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("13 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("14 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("15 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("16 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("17 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("18 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
,("19 FunReward","SOME SUPER CODE",1,"COOL_ITEM",NULL,NULL,NULL,NULL)
;
--  end  test.data
